# These settings are synced to GitHub by https://probot.github.io/apps/settings/

# Labels: define labels for Issues and Pull Requests
labels:
    - name: approved
      color: "#f9fcb0"
      description: "( ͡° ͜ °)"
    - name: bug
      color: "#d93f0b"
      description: "•`_´•"
    - name: dependencies
      color: "#AD1F93"
      description: "┬─┬ ノ( ゜-゜ノ)"
    - name: documentation
      color: "#0075ca"
      description: "♥"
    - name: done
      color: "#ededed"
      description: "⊂(◉‿◉)つ"
    - name: duplicate
      color: "#cfd3d7"
      description: "(づ｡◕‿‿◕｡)づ"
    - name: enhancement
      color: "#a2eeef"
      description: "٩( ๑╹ ꇴ╹)۶"
    - name: feature
      color: "#1d76db"
      description: "(͡ ° ͜ʖ ͡ °)"
    - name: good first issue
      color: "#7057ff"
      description: '※\(^o^)/※'
    - name: help
      color: "#d876e3"
      description: "☉ ‿ ⚆"
    - name: help wanted
      color: "#008672"
      description: "ಠ_ಠ"
    - name: in progress
      color: "#fbca04"
      description: "(✿◠‿◠)"
    - name: in review
      color: "#006b75"
      description: '\(°^°)/'
    - name: invalid
      color: "#fbca04"
      description: "(҂◡_◡) ᕤ"
    - name: merge conflict
      color: "#d93f0b"
      description: '/o\'
    - name: more information needed
      color: "#0052cc"
      description: '¯\(O_o)/¯'
    - name: neverstale
      color: "#D5863B"
      description: "ʕ·͡ᴥ·ʔ"
    - name: ready for review
      color: "#5319e7"
      description: "(☞ﾟヮﾟ)☞"
    - name: stale
      color: "#d4c5f9"
      description: "(-_-)"
    - name: support
      color: "#b60205"
      description: '\(°Ω°)/'
    - name: to do
      color: "#30baa0"
      description: "(ʘ‿ʘ)╯"
    - name: wontfix
      color: "#bfd4f2"
      description: "(⌐■_■)"
    - name: lock
      color: "#B60205"
      description: "ε(´סּ︵סּ`)з"
